-- Tabela e políticas para o módulo Documentos
-- Execute este script no SQL Editor do projeto Supabase usado pelo sistema.
-- Depois, execute também o arquivo supabase-documentos-storage.sql
-- para criar o bucket e as políticas do Storage.

create table if not exists public.documentos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  categoria text not null default 'Geral',
  descricao text,
  arquivo_nome text not null,
  mime text not null default 'application/pdf',
  size bigint not null default 0,
  data_url text,
  criado_por text,
  atualizado_em timestamptz not null default now(),
  publicado boolean not null default true
);

alter table public.documentos add column if not exists titulo text;
alter table public.documentos add column if not exists categoria text default 'Geral';
alter table public.documentos add column if not exists descricao text;
alter table public.documentos add column if not exists arquivo_nome text;
alter table public.documentos add column if not exists mime text default 'application/pdf';
alter table public.documentos add column if not exists size bigint default 0;
alter table public.documentos add column if not exists data_url text;
alter table public.documentos add column if not exists criado_por text;
alter table public.documentos add column if not exists atualizado_em timestamptz default now();
alter table public.documentos add column if not exists publicado boolean default true;

create index if not exists idx_documentos_categoria
  on public.documentos (categoria);

create index if not exists idx_documentos_publicado
  on public.documentos (publicado);

create index if not exists idx_documentos_atualizado
  on public.documentos (atualizado_em desc);

alter table public.documentos enable row level security;

drop policy if exists "Documentos select" on public.documentos;
create policy "Documentos select"
on public.documentos
for select
to public
using (true);

drop policy if exists "Documentos insert" on public.documentos;
create policy "Documentos insert"
on public.documentos
for insert
to public
with check (true);

drop policy if exists "Documentos update" on public.documentos;
create policy "Documentos update"
on public.documentos
for update
to public
using (true)
with check (true);

drop policy if exists "Documentos delete" on public.documentos;
create policy "Documentos delete"
on public.documentos
for delete
to public
using (true);
