-- Tabela do modulo Folha de Pagamento.
-- Execute no SQL Editor do mesmo projeto Supabase usado pelo sistema.
-- Depois, publique a Edge Function usuario-self-service atualizada deste projeto.

create table if not exists public.folha_pagamento_colaboradores (
  id bigint generated by default as identity primary key,
  nome text not null,
  cpf text not null,
  funcao text not null,
  salario numeric(14,2) not null check (salario > 0),
  chave_pix text not null,
  banco text not null,
  criado_por text,
  criado_por_id bigint,
  criado_por_email text,
  atualizado_em timestamptz not null default now(),
  constraint folha_pagamento_cpf_formato check (cpf ~ '^[0-9]{11}$'),
  constraint folha_pagamento_cpf_unique unique (cpf)
);

create index if not exists idx_folha_pagamento_colaboradores_nome
  on public.folha_pagamento_colaboradores (nome);

alter table public.folha_pagamento_colaboradores enable row level security;

revoke all on table public.folha_pagamento_colaboradores from anon, authenticated;

-- Sem politicas publicas de RLS: CPF, salario e PIX sao acessados apenas pela
-- Edge Function usuario-self-service, que valida sessao e perfil no servidor.
