-- Tabela e politicas para o modulo Agendamentos
-- Execute este script no SQL Editor do projeto Supabase usado pelo sistema.

create table if not exists public.agendamentos (
  id bigint generated by default as identity primary key,
  preenchido_em date not null,
  unidade text not null,
  equipe text not null,
  corretor_id bigint,
  corretor text not null,
  corretor_email text,
  cliente text not null,
  telefone text not null,
  data_agendamento date not null,
  horario_agendamento time without time zone not null,
  tipo_visita text not null check (tipo_visita in ('Primeiro atendimento', 'Fechamento', 'Envio de documentacao online')),
  canal_agendamento text not null default 'Presencial - escritorio' check (canal_agendamento in ('Presencial - escritorio', 'Online - WhatsApp')),
  criado_por text,
  criado_por_id bigint,
  criado_por_email text,
  situacao text not null default 'Agendado',
  tratativa_em timestamptz,
  tratativa_por text,
  tratativa_por_id bigint,
  tratativa_por_email text,
  reagendado_para_data date,
  reagendado_para_horario time without time zone,
  origem_agendamento_id bigint,
  novo_agendamento_id bigint,
  ref_local text,
  atualizado_em timestamptz not null default now()
);

alter table public.agendamentos add column if not exists criado_por_id bigint;
alter table public.agendamentos add column if not exists criado_por_email text;
alter table public.agendamentos add column if not exists situacao text default 'Agendado';
alter table public.agendamentos add column if not exists canal_agendamento text default 'Presencial - escritorio';
alter table public.agendamentos add column if not exists tratativa_em timestamptz;
alter table public.agendamentos add column if not exists tratativa_por text;
alter table public.agendamentos add column if not exists tratativa_por_id bigint;
alter table public.agendamentos add column if not exists tratativa_por_email text;
alter table public.agendamentos add column if not exists reagendado_para_data date;
alter table public.agendamentos add column if not exists reagendado_para_horario time without time zone;
alter table public.agendamentos add column if not exists origem_agendamento_id bigint;
alter table public.agendamentos add column if not exists novo_agendamento_id bigint;
alter table public.agendamentos add column if not exists ref_local text;

alter table public.agendamentos drop constraint if exists agendamentos_tipo_visita_check;
alter table public.agendamentos add constraint agendamentos_tipo_visita_check
  check (tipo_visita in ('Primeiro atendimento', 'Fechamento', 'Envio de documentacao online'));

alter table public.agendamentos drop constraint if exists agendamentos_canal_agendamento_check;
alter table public.agendamentos add constraint agendamentos_canal_agendamento_check
  check (canal_agendamento in ('Presencial - escritorio', 'Online - WhatsApp'));

update public.agendamentos
set canal_agendamento = case
  when coalesce(tipo_visita, '') = 'Envio de documentacao online' then 'Online - WhatsApp'
  else 'Presencial - escritorio'
end
where canal_agendamento is null or btrim(canal_agendamento) = '';

alter table public.agendamentos alter column canal_agendamento set default 'Presencial - escritorio';
alter table public.agendamentos alter column canal_agendamento set not null;

create index if not exists idx_agendamentos_data
  on public.agendamentos (data_agendamento, horario_agendamento);

create index if not exists idx_agendamentos_unidade
  on public.agendamentos (unidade, equipe);

create index if not exists idx_agendamentos_corretor
  on public.agendamentos (corretor_id, corretor_email);

create unique index if not exists idx_agendamentos_ref_local
  on public.agendamentos (ref_local)
  where ref_local is not null;

create or replace function public.agendamentos_normalizar_telefone(valor text)
returns text
language sql
immutable
as $$
  with base as (
    select regexp_replace(coalesce(valor, ''), '\D', '', 'g') as digitos
  )
  select left(
    case
      when length(digitos) in (12, 13) and left(digitos, 2) = '55' then substr(digitos, 3)
      else digitos
    end,
    11
  )
  from base;
$$;

create index if not exists idx_agendamentos_telefone_ativo
  on public.agendamentos (public.agendamentos_normalizar_telefone(telefone))
  where coalesce(situacao, 'Agendado') = 'Agendado';

create or replace function public.agendamentos_bloquear_telefone_duplicado()
returns trigger
language plpgsql
as $$
declare
  telefone_normalizado text;
  conflito record;
begin
  if coalesce(new.situacao, 'Agendado') <> 'Agendado' then
    return new;
  end if;

  telefone_normalizado := public.agendamentos_normalizar_telefone(new.telefone);
  if telefone_normalizado = '' then
    return new;
  end if;

  select
    a.id,
    a.cliente,
    a.corretor,
    a.data_agendamento,
    a.horario_agendamento
  into conflito
  from public.agendamentos a
  where coalesce(a.situacao, 'Agendado') = 'Agendado'
    and public.agendamentos_normalizar_telefone(a.telefone) = telefone_normalizado
    and (tg_op <> 'UPDATE' or a.id <> new.id)
  order by a.data_agendamento asc, a.horario_agendamento asc, a.id asc
  limit 1;

  if found then
    raise exception
      'AGENDAMENTO_TELEFONE_DUPLICADO: Ja existe um compromisso em aberto para este telefone. Cliente: %, corretor: %, data: %, horario: %.',
      coalesce(conflito.cliente, 'Sem cliente'),
      coalesce(conflito.corretor, 'Sem corretor'),
      conflito.data_agendamento,
      conflito.horario_agendamento
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_agendamentos_bloquear_telefone_duplicado on public.agendamentos;
create trigger trg_agendamentos_bloquear_telefone_duplicado
before insert or update of telefone, situacao
on public.agendamentos
for each row
execute function public.agendamentos_bloquear_telefone_duplicado();

alter table public.agendamentos enable row level security;

drop policy if exists "Agendamentos select" on public.agendamentos;
create policy "Agendamentos select"
on public.agendamentos
for select
to public
using (true);

drop policy if exists "Agendamentos insert" on public.agendamentos;
create policy "Agendamentos insert"
on public.agendamentos
for insert
to public
with check (true);

drop policy if exists "Agendamentos update" on public.agendamentos;
create policy "Agendamentos update"
on public.agendamentos
for update
to public
using (true)
with check (true);

drop policy if exists "Agendamentos delete" on public.agendamentos;
create policy "Agendamentos delete"
on public.agendamentos
for delete
to public
using (true);
