-- Tabela e politicas para o modulo Financeiro / Caixa
-- Execute este script no SQL Editor do projeto Supabase usado pelo sistema.
-- Para comprovantes em PDF/imagem, execute tambem o arquivo supabase-documentos-storage.sql.

create table if not exists public.financeiro_lancamentos (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('entrada', 'saida')),
  categoria text not null,
  descricao text not null,
  status text not null default 'previsto' check (status in ('previsto', 'realizado')),
  valor numeric(14,2) not null check (valor >= 0),
  unidade text,
  data_prevista date not null,
  data_realizada date,
  observacao text,
  comprovante_nome text,
  comprovante_mime text,
  comprovante_size bigint,
  comprovante_data_url text,
  comprovante_storage_bucket text,
  comprovante_storage_path text,
  criado_por text,
  criado_por_id bigint,
  criado_por_email text,
  atualizado_em timestamptz not null default now(),
  ref_local text,
  sync_pendente boolean not null default false,
  sync_erro text
);

alter table public.financeiro_lancamentos add column if not exists tipo text;
alter table public.financeiro_lancamentos add column if not exists categoria text;
alter table public.financeiro_lancamentos add column if not exists descricao text;
alter table public.financeiro_lancamentos add column if not exists status text default 'previsto';
alter table public.financeiro_lancamentos add column if not exists valor numeric(14,2) default 0;
alter table public.financeiro_lancamentos add column if not exists unidade text;
alter table public.financeiro_lancamentos add column if not exists data_prevista date;
alter table public.financeiro_lancamentos add column if not exists data_realizada date;
alter table public.financeiro_lancamentos add column if not exists observacao text;
alter table public.financeiro_lancamentos add column if not exists comprovante_nome text;
alter table public.financeiro_lancamentos add column if not exists comprovante_mime text;
alter table public.financeiro_lancamentos add column if not exists comprovante_size bigint;
alter table public.financeiro_lancamentos add column if not exists comprovante_data_url text;
alter table public.financeiro_lancamentos add column if not exists comprovante_storage_bucket text;
alter table public.financeiro_lancamentos add column if not exists comprovante_storage_path text;
alter table public.financeiro_lancamentos add column if not exists criado_por text;
alter table public.financeiro_lancamentos add column if not exists criado_por_id bigint;
alter table public.financeiro_lancamentos add column if not exists criado_por_email text;
alter table public.financeiro_lancamentos add column if not exists atualizado_em timestamptz default now();
alter table public.financeiro_lancamentos add column if not exists ref_local text;
alter table public.financeiro_lancamentos add column if not exists sync_pendente boolean default false;
alter table public.financeiro_lancamentos add column if not exists sync_erro text;

create index if not exists idx_financeiro_lancamentos_tipo_data
  on public.financeiro_lancamentos (tipo, data_prevista);

create index if not exists idx_financeiro_lancamentos_unidade
  on public.financeiro_lancamentos (unidade, data_prevista);

create unique index if not exists idx_financeiro_lancamentos_ref_local
  on public.financeiro_lancamentos (ref_local)
  where ref_local is not null;

alter table public.financeiro_lancamentos enable row level security;

drop policy if exists "Financeiro lancamentos select" on public.financeiro_lancamentos;
create policy "Financeiro lancamentos select"
on public.financeiro_lancamentos
for select
to public
using (true);

drop policy if exists "Financeiro lancamentos insert" on public.financeiro_lancamentos;
create policy "Financeiro lancamentos insert"
on public.financeiro_lancamentos
for insert
to public
with check (true);

drop policy if exists "Financeiro lancamentos update" on public.financeiro_lancamentos;
create policy "Financeiro lancamentos update"
on public.financeiro_lancamentos
for update
to public
using (true)
with check (true);

drop policy if exists "Financeiro lancamentos delete" on public.financeiro_lancamentos;
create policy "Financeiro lancamentos delete"
on public.financeiro_lancamentos
for delete
to public
using (true);
