-- Tabela e politicas para o modulo Agendamentos
-- Execute este script no SQL Editor do projeto Supabase usado pelo sistema.

create table if not exists public.agendamentos (
  id bigint generated by default as identity primary key,
  preenchido_em date not null,
  unidade text not null,
  equipe text not null,
  corretor_id bigint,
  corretor text not null,
  corretor_email text,
  cliente text not null,
  telefone text not null,
  data_agendamento date not null,
  horario_agendamento time without time zone not null,
  tipo_visita text not null check (tipo_visita in ('Primeiro atendimento', 'Fechamento')),
  criado_por text,
  criado_por_id bigint,
  criado_por_email text,
  situacao text not null default 'Agendado',
  tratativa_em timestamptz,
  tratativa_por text,
  tratativa_por_id bigint,
  tratativa_por_email text,
  reagendado_para_data date,
  reagendado_para_horario time without time zone,
  origem_agendamento_id bigint,
  novo_agendamento_id bigint,
  ref_local text,
  atualizado_em timestamptz not null default now()
);

alter table public.agendamentos add column if not exists criado_por_id bigint;
alter table public.agendamentos add column if not exists criado_por_email text;
alter table public.agendamentos add column if not exists situacao text default 'Agendado';
alter table public.agendamentos add column if not exists tratativa_em timestamptz;
alter table public.agendamentos add column if not exists tratativa_por text;
alter table public.agendamentos add column if not exists tratativa_por_id bigint;
alter table public.agendamentos add column if not exists tratativa_por_email text;
alter table public.agendamentos add column if not exists reagendado_para_data date;
alter table public.agendamentos add column if not exists reagendado_para_horario time without time zone;
alter table public.agendamentos add column if not exists origem_agendamento_id bigint;
alter table public.agendamentos add column if not exists novo_agendamento_id bigint;
alter table public.agendamentos add column if not exists ref_local text;

create index if not exists idx_agendamentos_data
  on public.agendamentos (data_agendamento, horario_agendamento);

create index if not exists idx_agendamentos_unidade
  on public.agendamentos (unidade, equipe);

create index if not exists idx_agendamentos_corretor
  on public.agendamentos (corretor_id, corretor_email);

create unique index if not exists idx_agendamentos_ref_local
  on public.agendamentos (ref_local)
  where ref_local is not null;

alter table public.agendamentos enable row level security;

drop policy if exists "Agendamentos select" on public.agendamentos;
create policy "Agendamentos select"
on public.agendamentos
for select
to public
using (true);

drop policy if exists "Agendamentos insert" on public.agendamentos;
create policy "Agendamentos insert"
on public.agendamentos
for insert
to public
with check (true);

drop policy if exists "Agendamentos update" on public.agendamentos;
create policy "Agendamentos update"
on public.agendamentos
for update
to public
using (true)
with check (true);

drop policy if exists "Agendamentos delete" on public.agendamentos;
create policy "Agendamentos delete"
on public.agendamentos
for delete
to public
using (true);
