-- Historico dos resumos diarios enviados aos donos via WhatsApp
-- Execute este script no SQL Editor do projeto Supabase usado pelo sistema.

create table if not exists public.owner_daily_reports (
  id bigint generated by default as identity primary key,
  report_ref text not null,
  data_referencia date not null,
  executado_em timestamptz not null default now(),
  trigger_reason text not null default 'manual',
  requested_by_user_id bigint,
  requested_by_name text,
  owner_user_id bigint,
  owner_name text not null,
  owner_phone text,
  snapshot_json jsonb not null default '{}'::jsonb,
  message_base text,
  message_final text,
  used_ai boolean not null default false,
  ai_error text,
  send_status text not null default 'pendente',
  send_error text,
  zapi_message_id text,
  zapi_zaap_id text,
  payload_envio jsonb,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table public.owner_daily_reports add column if not exists report_ref text;
alter table public.owner_daily_reports add column if not exists data_referencia date;
alter table public.owner_daily_reports add column if not exists executado_em timestamptz default now();
alter table public.owner_daily_reports add column if not exists trigger_reason text default 'manual';
alter table public.owner_daily_reports add column if not exists requested_by_user_id bigint;
alter table public.owner_daily_reports add column if not exists requested_by_name text;
alter table public.owner_daily_reports add column if not exists owner_user_id bigint;
alter table public.owner_daily_reports add column if not exists owner_name text;
alter table public.owner_daily_reports add column if not exists owner_phone text;
alter table public.owner_daily_reports add column if not exists snapshot_json jsonb default '{}'::jsonb;
alter table public.owner_daily_reports add column if not exists message_base text;
alter table public.owner_daily_reports add column if not exists message_final text;
alter table public.owner_daily_reports add column if not exists used_ai boolean default false;
alter table public.owner_daily_reports add column if not exists ai_error text;
alter table public.owner_daily_reports add column if not exists send_status text default 'pendente';
alter table public.owner_daily_reports add column if not exists send_error text;
alter table public.owner_daily_reports add column if not exists zapi_message_id text;
alter table public.owner_daily_reports add column if not exists zapi_zaap_id text;
alter table public.owner_daily_reports add column if not exists payload_envio jsonb;
alter table public.owner_daily_reports add column if not exists criado_em timestamptz default now();
alter table public.owner_daily_reports add column if not exists atualizado_em timestamptz default now();

alter table public.owner_daily_reports drop constraint if exists owner_daily_reports_trigger_reason_check;
alter table public.owner_daily_reports add constraint owner_daily_reports_trigger_reason_check
  check (trigger_reason in ('manual', 'scheduled', 'preview'));

alter table public.owner_daily_reports drop constraint if exists owner_daily_reports_send_status_check;
alter table public.owner_daily_reports add constraint owner_daily_reports_send_status_check
  check (send_status in ('pendente', 'enfileirada', 'falha', 'ignorado'));

create index if not exists idx_owner_daily_reports_ref
  on public.owner_daily_reports (report_ref);

create index if not exists idx_owner_daily_reports_data
  on public.owner_daily_reports (data_referencia desc, executado_em desc);

create index if not exists idx_owner_daily_reports_owner
  on public.owner_daily_reports (owner_user_id, executado_em desc);

create index if not exists idx_owner_daily_reports_status
  on public.owner_daily_reports (send_status, executado_em desc);

alter table public.owner_daily_reports enable row level security;
