-- Estrutura de notificacoes de evolucao de vendas via Z-API
-- Execute este script no SQL Editor do projeto Supabase usado pelo sistema.

create table if not exists public.venda_notificacoes_zapi (
  id bigint generated by default as identity primary key,
  venda_id bigint not null,
  venda_ref_local text,
  etapa_anterior integer,
  etapa_anterior_nome text,
  etapa_nova integer not null,
  etapa_nova_nome text not null,
  responsavel_avanco text,
  destinatario_usuario_id bigint,
  destinatario_nome text not null,
  destinatario_perfil text,
  destinatario_papel text not null,
  destinatario_papeis jsonb not null default '[]'::jsonb,
  telefone_bruto text,
  telefone_e164 text,
  mensagem text not null,
  canal text not null default 'whatsapp_zapi',
  status text not null default 'pendente',
  tentativas integer not null default 0,
  dedupe_key text,
  zapi_instance_id text,
  zapi_zaap_id text,
  zapi_message_id text,
  erro text,
  payload_envio jsonb,
  payload_delivery jsonb,
  payload_status jsonb,
  enviado_em timestamptz,
  recebido_em timestamptz,
  lido_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table public.venda_notificacoes_zapi add column if not exists venda_ref_local text;
alter table public.venda_notificacoes_zapi add column if not exists etapa_anterior integer;
alter table public.venda_notificacoes_zapi add column if not exists etapa_anterior_nome text;
alter table public.venda_notificacoes_zapi add column if not exists etapa_nova integer;
alter table public.venda_notificacoes_zapi add column if not exists etapa_nova_nome text;
alter table public.venda_notificacoes_zapi add column if not exists responsavel_avanco text;
alter table public.venda_notificacoes_zapi add column if not exists destinatario_usuario_id bigint;
alter table public.venda_notificacoes_zapi add column if not exists destinatario_nome text;
alter table public.venda_notificacoes_zapi add column if not exists destinatario_perfil text;
alter table public.venda_notificacoes_zapi add column if not exists destinatario_papel text;
alter table public.venda_notificacoes_zapi add column if not exists destinatario_papeis jsonb default '[]'::jsonb;
alter table public.venda_notificacoes_zapi add column if not exists telefone_bruto text;
alter table public.venda_notificacoes_zapi add column if not exists telefone_e164 text;
alter table public.venda_notificacoes_zapi add column if not exists mensagem text;
alter table public.venda_notificacoes_zapi add column if not exists canal text default 'whatsapp_zapi';
alter table public.venda_notificacoes_zapi add column if not exists status text default 'pendente';
alter table public.venda_notificacoes_zapi add column if not exists tentativas integer default 0;
alter table public.venda_notificacoes_zapi add column if not exists dedupe_key text;
alter table public.venda_notificacoes_zapi add column if not exists zapi_instance_id text;
alter table public.venda_notificacoes_zapi add column if not exists zapi_zaap_id text;
alter table public.venda_notificacoes_zapi add column if not exists zapi_message_id text;
alter table public.venda_notificacoes_zapi add column if not exists erro text;
alter table public.venda_notificacoes_zapi add column if not exists payload_envio jsonb;
alter table public.venda_notificacoes_zapi add column if not exists payload_delivery jsonb;
alter table public.venda_notificacoes_zapi add column if not exists payload_status jsonb;
alter table public.venda_notificacoes_zapi add column if not exists enviado_em timestamptz;
alter table public.venda_notificacoes_zapi add column if not exists recebido_em timestamptz;
alter table public.venda_notificacoes_zapi add column if not exists lido_em timestamptz;
alter table public.venda_notificacoes_zapi add column if not exists criado_em timestamptz default now();
alter table public.venda_notificacoes_zapi add column if not exists atualizado_em timestamptz default now();

alter table public.venda_notificacoes_zapi drop constraint if exists venda_notificacoes_zapi_status_check;
alter table public.venda_notificacoes_zapi add constraint venda_notificacoes_zapi_status_check
  check (status in (
    'pendente',
    'sem_telefone',
    'usuario_inativo',
    'ignorado',
    'enfileirada',
    'enviada',
    'recebida',
    'lida',
    'falha'
  ));

alter table public.venda_notificacoes_zapi drop constraint if exists venda_notificacoes_zapi_canal_check;
alter table public.venda_notificacoes_zapi add constraint venda_notificacoes_zapi_canal_check
  check (canal in ('whatsapp_zapi'));

create index if not exists idx_venda_notificacoes_zapi_venda
  on public.venda_notificacoes_zapi (venda_id, etapa_nova);

create index if not exists idx_venda_notificacoes_zapi_status
  on public.venda_notificacoes_zapi (status, criado_em desc);

create index if not exists idx_venda_notificacoes_zapi_message_id
  on public.venda_notificacoes_zapi (zapi_message_id);

create index if not exists idx_venda_notificacoes_zapi_zaap_id
  on public.venda_notificacoes_zapi (zapi_zaap_id);

create unique index if not exists idx_venda_notificacoes_zapi_dedupe
  on public.venda_notificacoes_zapi (dedupe_key)
  where dedupe_key is not null;

create table if not exists public.venda_notificacoes_zapi_eventos (
  id bigint generated by default as identity primary key,
  tipo text not null,
  instance_id text,
  phone text,
  message_id text,
  payload jsonb not null,
  criado_em timestamptz not null default now()
);

alter table public.venda_notificacoes_zapi_eventos add column if not exists tipo text;
alter table public.venda_notificacoes_zapi_eventos add column if not exists instance_id text;
alter table public.venda_notificacoes_zapi_eventos add column if not exists phone text;
alter table public.venda_notificacoes_zapi_eventos add column if not exists message_id text;
alter table public.venda_notificacoes_zapi_eventos add column if not exists payload jsonb;
alter table public.venda_notificacoes_zapi_eventos add column if not exists criado_em timestamptz default now();

alter table public.venda_notificacoes_zapi_eventos drop constraint if exists venda_notificacoes_zapi_eventos_tipo_check;
alter table public.venda_notificacoes_zapi_eventos add constraint venda_notificacoes_zapi_eventos_tipo_check
  check (tipo in ('delivery', 'status'));

create index if not exists idx_venda_notificacoes_zapi_eventos_tipo
  on public.venda_notificacoes_zapi_eventos (tipo, criado_em desc);

create index if not exists idx_venda_notificacoes_zapi_eventos_message
  on public.venda_notificacoes_zapi_eventos (message_id);

alter table public.venda_notificacoes_zapi enable row level security;
alter table public.venda_notificacoes_zapi_eventos enable row level security;

drop policy if exists "Venda notificacoes zapi select" on public.venda_notificacoes_zapi;
create policy "Venda notificacoes zapi select"
on public.venda_notificacoes_zapi
for select
to public
using (true);

drop policy if exists "Venda notificacoes zapi eventos select" on public.venda_notificacoes_zapi_eventos;
create policy "Venda notificacoes zapi eventos select"
on public.venda_notificacoes_zapi_eventos
for select
to public
using (true);
