-- Modulo Reembolsos de ATO
-- A migracao oficial esta em supabase/migrations/20260911120000_reembolsos_ato.sql.

create table if not exists public.reembolsos_ato (
  id bigint generated by default as identity primary key,
  cliente text not null,
  telefone text not null,
  valor numeric(14,2) not null check (valor > 0),
  data_prevista date not null,
  banco text not null,
  chave_pix text not null,
  status text not null default 'pendente' check (status in ('pendente', 'reembolsado')),
  data_reembolso date,
  financeiro_lancamento_id bigint references public.financeiro_lancamentos(id) on delete set null,
  comprovante_nome text,
  comprovante_mime text,
  comprovante_size bigint,
  comprovante_storage_bucket text,
  comprovante_storage_path text,
  criado_por text,
  criado_por_id bigint,
  criado_por_email text,
  atualizado_em timestamptz not null default now(),
  constraint reembolsos_ato_status_data_check check (
    (status = 'pendente' and data_reembolso is null)
    or (status = 'reembolsado' and data_reembolso is not null)
  )
);

create index if not exists idx_reembolsos_ato_status_data
  on public.reembolsos_ato (status, data_prevista);

create index if not exists idx_reembolsos_ato_cliente
  on public.reembolsos_ato (cliente);

create unique index if not exists idx_reembolsos_ato_financeiro
  on public.reembolsos_ato (financeiro_lancamento_id)
  where financeiro_lancamento_id is not null;

alter table public.reembolsos_ato enable row level security;

revoke all on table public.reembolsos_ato from anon, authenticated;

-- Sem politicas publicas de RLS: telefone, banco e PIX sao acessados apenas pela
-- Edge Function usuario-self-service, que valida sessao e perfil no servidor.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'reembolsos-ato',
  'reembolsos-ato',
  false,
  10485760,
  array['application/pdf','image/jpeg','image/png','image/webp','image/jpg']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Exclusao atomica do registro e de sua saida automatica no Financeiro.
-- Somente a Edge Function com service_role pode executar esta operacao.
create or replace function public.excluir_reembolso_ato_completo(p_id bigint)
returns table (
  reembolso_id bigint,
  financeiro_lancamento_id_removido bigint,
  comprovante_storage_bucket_removido text,
  comprovante_storage_path_removido text
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_reembolso public.reembolsos_ato%rowtype;
begin
  select r.*
    into v_reembolso
    from public.reembolsos_ato r
   where r.id = p_id
   for update;

  if not found then
    return;
  end if;

  delete from public.financeiro_lancamentos f
   where f.ref_local = ('fin-reembolso-ato-' || p_id::text)
      or (
        v_reembolso.financeiro_lancamento_id is not null
        and f.id = v_reembolso.financeiro_lancamento_id
      );

  delete from public.reembolsos_ato r
   where r.id = p_id;

  return query
  select
    v_reembolso.id,
    v_reembolso.financeiro_lancamento_id,
    v_reembolso.comprovante_storage_bucket,
    v_reembolso.comprovante_storage_path;
end;
$$;

revoke all on function public.excluir_reembolso_ato_completo(bigint)
  from public, anon, authenticated;

grant execute on function public.excluir_reembolso_ato_completo(bigint)
  to service_role;
