-- Suporte ao fluxo de contrato de parceria (Corretor PJ) assinado via
-- Clicksign antes da liberação do convite de acesso ao sistema.
--
-- Fluxo:
--  1. Diretor preenche o convite de um Corretor com os dados do MEI
--     (nome_empresa, cnpj, endereço da empresa). Em vez de criar o
--     usuário/convite de acesso na hora, a Edge Function
--     `usuario-self-service` (ação create_user_contract) gera o
--     documento no Clicksign a partir do modelo e grava uma linha
--     "aguardando_assinatura" em `contratos_clicksign_pendentes`.
--  2. O Clicksign notifica a Edge Function `clicksign-webhook` quando o
--     documento é finalizado (todas as assinaturas concluídas).
--  3. O webhook marca o registro como "assinado" e só então chama
--     `registrar_convite_usuario` (já existente) para criar o usuário
--     "Pendente" e o convite de acesso — replicando o fluxo que hoje
--     acontece na hora, para os demais perfis.

alter table public.usuarios
  add column if not exists nome_empresa text,
  add column if not exists cnpj_empresa text,
  add column if not exists endereco_empresa text,
  add column if not exists contrato_status text,
  add column if not exists contrato_clicksign_envelope_key text,
  add column if not exists contrato_enviado_em timestamptz,
  add column if not exists contrato_assinado_em timestamptz;

comment on column public.usuarios.nome_empresa is
  'Razão social do MEI/empresa do corretor, usada no contrato de parceria via Clicksign.';
comment on column public.usuarios.cnpj_empresa is
  'CNPJ do MEI/empresa do corretor.';
comment on column public.usuarios.endereco_empresa is
  'Endereço da sede do MEI/empresa do corretor, conforme qualificado no contrato.';
comment on column public.usuarios.contrato_status is
  'Status do contrato de parceria via Clicksign: aguardando_assinatura | assinado | cancelado. Nulo para perfis sem esse fluxo.';

create table if not exists public.contratos_clicksign_pendentes (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null,
  perfil text not null,
  equipe text,
  unidade text not null,
  rh_contratacao boolean not null default false,
  nome_empresa text not null,
  cnpj_empresa text not null,
  endereco_empresa text not null,
  clicksign_envelope_key text not null unique,
  clicksign_document_key text,
  status text not null default 'aguardando_assinatura'
    check (status in ('aguardando_assinatura', 'assinado', 'cancelado')),
  usuario_id bigint references public.usuarios(id) on delete set null,
  criado_por text,
  criado_por_id bigint,
  criado_por_email text,
  criado_em timestamptz not null default now(),
  assinado_em timestamptz,
  erro text
);

create index if not exists idx_contratos_clicksign_pendentes_status
  on public.contratos_clicksign_pendentes (status, criado_em desc);

create index if not exists idx_contratos_clicksign_pendentes_email
  on public.contratos_clicksign_pendentes (lower(email));

alter table public.contratos_clicksign_pendentes enable row level security;

revoke all on table public.contratos_clicksign_pendentes from public, anon, authenticated;

-- Log bruto de toda chamada recebida no webhook do Clicksign, para permitir
-- depurar o formato real do payload (a documentação pública não expõe os
-- exemplos completos) sem precisar adivinhar. Mesma ideia de
-- `venda_notificacoes_zapi_eventos`, já usada no projeto.
create table if not exists public.clicksign_webhook_eventos (
  id bigint generated by default as identity primary key,
  evento text,
  payload jsonb not null,
  contrato_id bigint references public.contratos_clicksign_pendentes(id) on delete set null,
  processado boolean not null default false,
  erro text,
  criado_em timestamptz not null default now()
);

alter table public.clicksign_webhook_eventos enable row level security;

revoke all on table public.clicksign_webhook_eventos from public, anon, authenticated;
