create table if not exists public.financeiro_saldos_bancarios (
  id bigint generated by default as identity primary key,
  conta text not null default 'CONTA PRINCIPAL',
  data_referencia date not null,
  saldo_bancario numeric(14,2) not null,
  observacao text,
  criado_por text,
  criado_por_id bigint,
  criado_por_email text,
  atualizado_em timestamptz not null default now(),
  unique (conta, data_referencia)
);

create index if not exists idx_financeiro_saldos_bancarios_data
  on public.financeiro_saldos_bancarios (data_referencia);

alter table public.financeiro_saldos_bancarios enable row level security;

drop policy if exists "Financeiro saldos bancarios select" on public.financeiro_saldos_bancarios;
create policy "Financeiro saldos bancarios select"
on public.financeiro_saldos_bancarios for select to public using (true);

drop policy if exists "Financeiro saldos bancarios insert" on public.financeiro_saldos_bancarios;
create policy "Financeiro saldos bancarios insert"
on public.financeiro_saldos_bancarios for insert to public with check (true);

drop policy if exists "Financeiro saldos bancarios update" on public.financeiro_saldos_bancarios;
create policy "Financeiro saldos bancarios update"
on public.financeiro_saldos_bancarios for update to public using (true) with check (true);

drop policy if exists "Financeiro saldos bancarios delete" on public.financeiro_saldos_bancarios;
create policy "Financeiro saldos bancarios delete"
on public.financeiro_saldos_bancarios for delete to public using (true);
