create table if not exists public.reembolsos_ato (
  id bigint generated by default as identity primary key,
  cliente text not null,
  telefone text not null,
  valor numeric(14,2) not null check (valor > 0),
  data_prevista date not null,
  banco text not null,
  chave_pix text not null,
  status text not null default 'pendente' check (status in ('pendente', 'reembolsado')),
  data_reembolso date,
  financeiro_lancamento_id bigint references public.financeiro_lancamentos(id) on delete set null,
  criado_por text,
  criado_por_id bigint,
  criado_por_email text,
  atualizado_em timestamptz not null default now(),
  constraint reembolsos_ato_status_data_check check (
    (status = 'pendente' and data_reembolso is null)
    or (status = 'reembolsado' and data_reembolso is not null)
  )
);

create index if not exists idx_reembolsos_ato_status_data
  on public.reembolsos_ato (status, data_prevista);

create index if not exists idx_reembolsos_ato_cliente
  on public.reembolsos_ato (cliente);

create unique index if not exists idx_reembolsos_ato_financeiro
  on public.reembolsos_ato (financeiro_lancamento_id)
  where financeiro_lancamento_id is not null;

alter table public.reembolsos_ato enable row level security;

revoke all on table public.reembolsos_ato from anon, authenticated;

-- Sem politicas publicas de RLS: telefone, banco e PIX sao acessados apenas pela
-- Edge Function usuario-self-service, que valida sessao e perfil no servidor.
