create table if not exists public.convites_usuarios (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  token_hash text not null unique,
  nome text not null,
  email text not null,
  perfil text not null,
  equipe text,
  unidade text not null,
  rh_contratacao boolean not null default false,
  expira_em timestamptz not null,
  usado_em timestamptz,
  revogado_em timestamptz,
  criado_por text,
  criado_por_id bigint,
  criado_por_email text,
  criado_em timestamptz not null default now(),
  constraint convites_usuarios_token_hash_check check (token_hash ~ '^[0-9a-f]{64}$')
);

create index if not exists idx_convites_usuarios_email
  on public.convites_usuarios (lower(email), criado_em desc);

create index if not exists idx_convites_usuarios_validade
  on public.convites_usuarios (expira_em)
  where usado_em is null and revogado_em is null;

alter table public.convites_usuarios enable row level security;

revoke all on table public.convites_usuarios from public, anon, authenticated;

create or replace function public.registrar_convite_usuario(
  p_token_hash text,
  p_nome text,
  p_email text,
  p_perfil text,
  p_equipe text,
  p_unidade text,
  p_rh_contratacao boolean,
  p_expira_em timestamptz,
  p_criado_por text,
  p_criado_por_id bigint,
  p_criado_por_email text
)
returns table (usuario_id bigint, convite_id bigint)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_usuario_id bigint;
  v_convite_id bigint;
  v_status text;
begin
  if coalesce(trim(p_token_hash), '') !~ '^[0-9a-f]{64}$'
     or coalesce(trim(p_nome), '') = ''
     or coalesce(trim(p_email), '') = ''
     or coalesce(trim(p_perfil), '') = ''
     or coalesce(trim(p_unidade), '') = ''
     or p_expira_em <= now() then
    raise exception using errcode = '22023', message = 'Dados inválidos para registrar o convite.';
  end if;

  select u.id, u.status
    into v_usuario_id, v_status
    from public.usuarios u
   where lower(trim(u.email)) = lower(trim(p_email))
   for update;

  if found then
    if lower(trim(coalesce(v_status, ''))) <> 'pendente' then
      raise exception using errcode = '23505', message = 'Este e-mail já possui um usuário ativo ou inativo.';
    end if;

    update public.usuarios
       set nome = trim(p_nome),
           email = lower(trim(p_email)),
           perfil = trim(p_perfil),
           equipe = coalesce(trim(p_equipe), ''),
           unidade = trim(p_unidade),
           rh_contratacao = coalesce(p_rh_contratacao, false),
           status = 'Pendente'
     where id = v_usuario_id;
  else
    insert into public.usuarios (
      nome, email, tel, perfil, status, unidade, equipe,
      banco, agencia, conta, tipo_conta, pix_tipo, pix,
      cpf, nasc, cep, endereco, cidade, estado, rh_contratacao,
      data_ativacao, data_inativacao, historico_status
    ) values (
      trim(p_nome), lower(trim(p_email)), '', trim(p_perfil), 'Pendente', trim(p_unidade), coalesce(trim(p_equipe), ''),
      '', '', '', '', '', '',
      '', '', '', '', '', '', coalesce(p_rh_contratacao, false),
      null, null, '[]'::jsonb
    )
    returning id into v_usuario_id;
  end if;

  update public.convites_usuarios
     set revogado_em = now()
   where lower(trim(email)) = lower(trim(p_email))
     and usado_em is null
     and revogado_em is null;

  insert into public.convites_usuarios (
    usuario_id, token_hash, nome, email, perfil, equipe, unidade,
    rh_contratacao, expira_em, criado_por, criado_por_id, criado_por_email
  ) values (
    v_usuario_id, trim(p_token_hash), trim(p_nome), lower(trim(p_email)), trim(p_perfil),
    coalesce(trim(p_equipe), ''), trim(p_unidade), coalesce(p_rh_contratacao, false),
    p_expira_em, p_criado_por, p_criado_por_id, p_criado_por_email
  )
  returning id into v_convite_id;

  return query select v_usuario_id, v_convite_id;
end;
$$;

create or replace function public.concluir_convite_usuario(
  p_token_hash text,
  p_nome text,
  p_tel text,
  p_nasc text,
  p_cpf text,
  p_cep text,
  p_endereco text,
  p_cidade text,
  p_estado text,
  p_banco text,
  p_agencia text,
  p_conta text,
  p_tipo_conta text,
  p_pix_tipo text,
  p_pix text,
  p_senha text
)
returns table (usuario_id bigint, email text)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_convite public.convites_usuarios%rowtype;
  v_usuario_status text;
  v_data_ativacao date := (now() at time zone 'America/Sao_Paulo')::date;
begin
  select c.*
    into v_convite
    from public.convites_usuarios c
   where c.token_hash = trim(p_token_hash)
   for update;

  if not found or v_convite.usado_em is not null or v_convite.revogado_em is not null then
    raise exception using errcode = 'P0002', message = 'Convite inválido ou já utilizado.';
  end if;
  if v_convite.expira_em <= now() then
    raise exception using errcode = 'P0001', message = 'Este convite expirou. Solicite um novo convite.';
  end if;

  select u.status
    into v_usuario_status
    from public.usuarios u
   where u.id = v_convite.usuario_id
     and lower(trim(u.email)) = lower(trim(v_convite.email))
   for update;

  if not found or lower(trim(coalesce(v_usuario_status, ''))) <> 'pendente' then
    raise exception using errcode = 'P0002', message = 'O usuário deste convite não está mais pendente.';
  end if;

  update public.usuarios u
     set nome = trim(p_nome),
         tel = trim(p_tel),
         status = 'Ativo',
         banco = trim(p_banco),
         agencia = trim(p_agencia),
         conta = trim(p_conta),
         tipo_conta = trim(p_tipo_conta),
         pix_tipo = trim(p_pix_tipo),
         pix = trim(p_pix),
         cpf = trim(p_cpf),
         nasc = trim(p_nasc),
         cep = trim(p_cep),
         endereco = trim(p_endereco),
         cidade = trim(p_cidade),
         estado = upper(trim(p_estado)),
         data_ativacao = coalesce(u.data_ativacao, v_data_ativacao),
         data_inativacao = null,
         historico_status = coalesce(u.historico_status, '[]'::jsonb) || jsonb_build_array(
           jsonb_build_object(
             'tipo', 'ativado',
             'data', to_char(v_data_ativacao, 'DD/MM/YYYY'),
             'ts', to_char(now() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
             'por', 'Onboarding',
             'statusAnterior', 'Pendente',
             'statusNovo', 'Ativo',
             'origem', 'convite'
           )
         )
   where u.id = v_convite.usuario_id;

  update public.senhas s
     set senha = p_senha
   where s.email = lower(trim(v_convite.email));

  if not found then
    insert into public.senhas (email, senha)
    values (lower(trim(v_convite.email)), p_senha);
  end if;

  update public.convites_usuarios
     set usado_em = now()
   where id = v_convite.id;

  return query select v_convite.usuario_id, lower(trim(v_convite.email));
end;
$$;

revoke all on function public.registrar_convite_usuario(text,text,text,text,text,text,boolean,timestamptz,text,bigint,text)
  from public, anon, authenticated;
revoke all on function public.concluir_convite_usuario(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text)
  from public, anon, authenticated;

grant execute on function public.registrar_convite_usuario(text,text,text,text,text,text,boolean,timestamptz,text,bigint,text)
  to service_role;
grant execute on function public.concluir_convite_usuario(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text)
  to service_role;
